### ISSUE TITLE
Mic not working on Apple MacBook Pro (14-inch, M2 Pro, 2023)

### ISSUE THREAD

**Issue by luca-trigili** [AsahiLinux/asahi-audio#64]
Some debug outputs:

wpctl status:
```
PipeWire 'pipewire-0' [1.4.1, user@fedora, cookie:1864573131]
 └─ Clients:
        33. WirePlumber                         [1.4.1, user@fedora, pid:1555]
        34. pipewire                            [1.4.1, user@fedora, pid:1558]
        36. cosmic-osd                          [1.4.1, user@fedora, pid:1518]
        39. cosmic-osd                          [1.4.1, user@fedora, pid:1574]
        46. WirePlumber                         [1.4.1, user@fedora, pid:1555]
        47. Firefox                             [1.4.1, user@fedora, pid:3069]
        49. WirePlumber [export]                [1.4.1, user@fedora, pid:1555]
        52. xdg-desktop-portal                  [1.4.1, user@fedora, pid:1714]
        53. cosmic-osd                          [1.4.1, user@fedora, pid:1741]
        54. MainConn                            [1.4.1, user@fedora, pid:1741]
        89. wpctl                               [1.4.1, user@fedora, pid:6126]
        96. balance                             [1.4.1, user@fedora, pid:1741]
       105. Firefox                             [1.4.1, user@fedora, pid:3069]

Audio
 ├─ Devices:
 │      55. Built-in Audio                      [alsa]
 │      56. Built-in Audio                      [alsa]
 │
 ├─ Sinks:
 │      64. Built-in Audio Headphones           [vol: 1.00]
 │
 ├─ Sources:
 │      65. Built-in Audio Headset Microphone   [vol: 1.00]
 │
 ├─ Filters:
 │    - filter-chain-1555-19
 │  *   77. audio_effect.j414-convolver                                  [Audio/Sink]
 │      78. effect_output.j414-convolver                                 [Stream/Output/Audio]
 │
 └─ Streams:

Video
 ├─ Devices:
 │      45. FaceTime HD Camera                  [v4l2]
 │
 ├─ Sinks:
 │
 ├─ Sources:
 │  *   51. FaceTime HD Camera (V4L2)
 │
 ├─ Filters:
 │
 └─ Streams:

Settings
 └─ Default Configured Devices:
```

[pw-cli all](https://github.com/user-attachments/files/19633310/pw-cli.txt)

journalctl --user -u wireplumber.service:
```
-- Boot 469b8ebea67945dab4ab3bad8c6d7df8 --
apr 07 15:18:16 fedora systemd[1318]: Started wireplumber.service - Multimedia Service Session Manager.
apr 07 15:18:16 fedora wireplumber[1555]: wp-internal-comp-loader: Loading profile 'main'
apr 07 15:18:16 fedora wireplumber[1555]: spa.bluez5: Failed to start HFP/HSP backend native
apr 07 15:18:16 fedora wireplumber[1555]: [0:00:28.498314113] [1555]  INFO Camera camera_manager.cpp:327 libcamera v0.4.0
apr 07 15:18:16 fedora wireplumber[1555]: m-lua-scripting: <WpSpaPod:0xaaabb2a84b80> Forcing Speaker route props: <WpDevice:0xaaabb2a1b3a0>:
                                            Object: size 136, type Spa:Pod:Object:Param:Route (262153), id Spa:Enum:ParamId:Route (13)
                                              Prop: key Spa:Pod:Object:Param:Route:device (3), flags 00000000
                                                Int 0
                                              Prop: key Spa:Pod:Object:Param:Route:index (1), flags 00000000
                                                Int 0
                                              Prop: key Spa:Pod:Object:Param:Route:props (10), flags 00000000
                                                Object: size 64, type Spa:Pod:Object:Param:Props (262146), id Spa:Enum:ParamId:Route (13)
                                                  Prop: key Spa:Pod:Object:Param:Props:mute (65540), flags 00000000
                                                    Bool false
                                                  Prop: key Spa:Pod:Object:Param:Props:channelVolumes (65544), flags 00000000
                                                    Array: child.size 4, child.type Spa:Float
                                                      Float 1.000000
```

journalctl --user -u pipewire.service:
```
-- Boot 28daeffb6ac2473da8625fa769f366e5 --
apr 05 21:42:04 fedora systemd[1351]: Started pipewire.service - PipeWire Multimedia Service.
apr 05 23:09:22 fedora pipewire[1602]: spa.alsa: hw:AppleJ414,1p: (0 suppressed) snd_pcm_avail after recover: Broken pipe
apr 05 23:09:24 fedora systemd[1351]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 05 23:09:24 fedora systemd[1351]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 05 23:09:24 fedora systemd[1351]: pipewire.service: Consumed 3.119s CPU time, 19M memory peak.
-- Boot ea0a0dd637cf4ee1ae33c9e873535616 --
apr 06 16:34:08 fedora systemd[1362]: Started pipewire.service - PipeWire Multimedia Service.
apr 06 23:29:12 fedora systemd[1362]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 06 23:29:12 fedora systemd[1362]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 06 23:29:12 fedora systemd[1362]: pipewire.service: Consumed 39.391s CPU time, 20M memory peak, 4.9M memory swap peak.
-- Boot b47e71d9943e435fbc5abc251b5ccacd --
apr 07 15:06:55 fedora systemd[1307]: Started pipewire.service - PipeWire Multimedia Service.
apr 07 15:17:20 fedora systemd[1307]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 07 15:17:20 fedora systemd[1307]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 469b8ebea67945dab4ab3bad8c6d7df8 --
apr 07 15:18:16 fedora systemd[1318]: Started pipewire.service - PipeWire Multimedia Service.
```

**Comment by chadmed** [comment]
Looks like the hardware hasn't been picked up. Can you run asahi-diagnose and attach the output?

**Comment by luca-trigili** [comment]
[asahi-diagnose-20250408-084324.txt](https://github.com/user-attachments/files/19643980/asahi-diagnose-20250408-084324.txt)

**Comment by luca-trigili** [comment]
[asahi-diagnose-20250413-133237.txt](https://github.com/user-attachments/files/19725093/asahi-diagnose-20250413-133237.txt)

New diagnose after kernel update.

**Comment by chadmed** [comment]
Can you please go to `/usr/share/wireplumber/wireplumber.conf.d/99-asahi.conf`, find the entry that matches on `AppleJ414HPAI`, set `hide-parent = false`, run `systemctl restart --user wireplumber`, then post the output of:

`journalctl --user -u -- wireplumber`
`journalctl --user -u pipewire`
`wpctl status`
`pw-cli i all`

**Comment by luca-trigili** [comment]
**journalctl --user -u --wireplumber** --> No entries

**journalctl --user -u pipewire**
```bash
-- Boot 28daeffb6ac2473da8625fa769f366e5 --
apr 05 21:42:04 fedora systemd[1351]: Started pipewire.service - PipeWire Multimedia Service.
apr 05 23:09:22 fedora pipewire[1602]: spa.alsa: hw:AppleJ414,1p: (0 suppressed) snd_pcm_avail after r>
apr 05 23:09:24 fedora systemd[1351]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 05 23:09:24 fedora systemd[1351]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 05 23:09:24 fedora systemd[1351]: pipewire.service: Consumed 3.119s CPU time, 19M memory peak.
-- Boot ea0a0dd637cf4ee1ae33c9e873535616 --
apr 06 16:34:08 fedora systemd[1362]: Started pipewire.service - PipeWire Multimedia Service.
apr 06 23:29:12 fedora systemd[1362]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 06 23:29:12 fedora systemd[1362]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 06 23:29:12 fedora systemd[1362]: pipewire.service: Consumed 39.391s CPU time, 20M memory peak, 4.>
-- Boot b47e71d9943e435fbc5abc251b5ccacd --
apr 07 15:06:55 fedora systemd[1307]: Started pipewire.service - PipeWire Multimedia Service.
apr 07 15:17:20 fedora systemd[1307]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 07 15:17:20 fedora systemd[1307]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 469b8ebea67945dab4ab3bad8c6d7df8 --
apr 07 15:18:16 fedora systemd[1318]: Started pipewire.service - PipeWire Multimedia Service.
apr 07 17:57:59 fedora systemd[1318]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 07 17:57:59 fedora systemd[1318]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 07 17:57:59 fedora systemd[1318]: pipewire.service: Consumed 1.987s CPU time, 17.7M memory peak.
-- Boot 972fd6dcf0a942f0a5a074a607ce5dd2 --
apr 08 08:07:23 fedora systemd[1350]: Started pipewire.service - PipeWire Multimedia Service.
apr 08 08:23:14 fedora systemd[1350]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 08 08:23:14 fedora systemd[1350]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot aaa16ef00b9d4ed29d821fbbcaea7247 --
apr 08 08:43:17 fedora systemd[1323]: Started pipewire.service - PipeWire Multimedia Service.
apr 08 10:01:22 fedora systemd[1323]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 08 10:01:22 fedora systemd[1323]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 4354cf0744b04aa0a69134f6cfb41e7c --
apr 08 11:58:21 fedora systemd[1285]: Started pipewire.service - PipeWire Multimedia Service.
apr 08 13:19:38 fedora systemd[1285]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 08 13:19:38 fedora systemd[1285]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 2fe83463a570413fa4883f616688d75c --
apr 08 15:15:55 fedora systemd[1313]: Started pipewire.service - PipeWire Multimedia Service.
apr 08 16:45:22 fedora systemd[1313]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 08 16:45:22 fedora systemd[1313]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 08 16:45:22 fedora systemd[1313]: pipewire.service: Consumed 9.220s CPU time, 19.1M memory peak.
-- Boot 0f562253eb7141d4b37818684a455ab7 --
apr 08 23:43:18 fedora systemd[1365]: Started pipewire.service - PipeWire Multimedia Service.
apr 09 00:48:50 fedora systemd[1365]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 09 00:48:50 fedora systemd[1365]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 09 00:48:50 fedora systemd[1365]: pipewire.service: Consumed 4.966s CPU time, 17.5M memory peak.
-- Boot 36f9f4f92ebf49c39563bb106175c815 --
apr 09 09:32:31 fedora systemd[1325]: Started pipewire.service - PipeWire Multimedia Service.
apr 09 09:58:59 fedora systemd[1325]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 09 09:58:59 fedora systemd[1325]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot ae4626a616624d988fda614a77e5d392 --
apr 09 14:22:43 fedora systemd[1381]: Started pipewire.service - PipeWire Multimedia Service.
apr 10 00:39:15 fedora systemd[1381]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 10 00:39:15 fedora systemd[1381]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 10 00:39:15 fedora systemd[1381]: pipewire.service: Consumed 1.102s CPU time, 16.2M memory peak, 9>
-- Boot 7fd44cfcb6524e34a4381831e1a0d189 --
apr 10 09:13:34 fedora systemd[1321]: Started pipewire.service - PipeWire Multimedia Service.
apr 10 09:51:35 fedora systemd[1321]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 10 09:51:35 fedora systemd[1321]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot be11c23e63f243a9a1319fc5f91eb5c0 --
apr 10 09:53:12 fedora systemd[1325]: Started pipewire.service - PipeWire Multimedia Service.
apr 10 14:47:01 fedora systemd[1325]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 10 14:47:01 fedora systemd[1325]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot fa4635f9daa041b387987668765a7a2f --
apr 10 15:17:08 fedora systemd[1289]: Started pipewire.service - PipeWire Multimedia Service.
apr 10 19:15:11 fedora systemd[1289]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 10 19:15:11 fedora systemd[1289]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 97ebdedc85334e8d956b1726495082df --
apr 10 22:07:37 fedora systemd[1328]: Started pipewire.service - PipeWire Multimedia Service.
apr 11 00:04:32 fedora systemd[1328]: pipewire.service: A process of this unit has been killed by the >
apr 11 00:04:32 fedora systemd[1328]: pipewire.service: Main process exited, code=killed, status=9/KILL
apr 11 00:04:32 fedora systemd[1328]: pipewire.service: Failed with result 'oom-kill'.
apr 11 00:04:32 fedora systemd[1328]: pipewire.service: Consumed 4.822s CPU time, 17.9M memory peak, 1>
apr 11 00:04:32 fedora systemd[1328]: pipewire.service: Scheduled restart job, restart counter is at 1.
apr 11 00:04:32 fedora systemd[1328]: Started pipewire.service - PipeWire Multimedia Service.
apr 11 02:23:19 fedora systemd[1328]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 11 02:23:19 fedora systemd[1328]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 8676836da06745e2887d9b1ca8452c23 --
apr 11 02:24:24 fedora systemd[1289]: Started pipewire.service - PipeWire Multimedia Service.
apr 11 02:29:58 fedora systemd[1289]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 11 02:29:58 fedora systemd[1289]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot a82eaa32192645e49926dcb2ea0605c3 --
apr 11 06:59:50 fedora systemd[1325]: Started pipewire.service - PipeWire Multimedia Service.
apr 11 07:44:20 fedora systemd[1325]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 11 07:44:20 fedora systemd[1325]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 5ace99cfc6d64c79a56e63fa98204739 --
apr 11 08:11:21 fedora systemd[1293]: Started pipewire.service - PipeWire Multimedia Service.
apr 11 14:59:17 fedora systemd[1293]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 11 14:59:17 fedora systemd[1293]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 11 14:59:17 fedora systemd[1293]: pipewire.service: Consumed 3.783s CPU time, 19.4M memory peak.
-- Boot eb8c17c6a3fd4168946caae4e762a750 --
apr 11 19:09:11 fedora systemd[1330]: Started pipewire.service - PipeWire Multimedia Service.
apr 11 22:28:19 fedora systemd[1330]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 11 22:28:19 fedora systemd[1330]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 11 22:28:19 fedora systemd[1330]: pipewire.service: Consumed 1.390s CPU time, 15.6M memory peak, 4>
-- Boot 85f3767e5119454b91bd77f1025e7012 --
apr 11 22:29:54 fedora systemd[1334]: Started pipewire.service - PipeWire Multimedia Service.
apr 12 00:20:37 fedora systemd[1334]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 12 00:20:37 fedora systemd[1334]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 12 00:20:37 fedora systemd[1334]: pipewire.service: Consumed 1.885s CPU time, 18.7M memory peak.
-- Boot 0c3dbc64b1e24d3fafe4594d28294d1c --
apr 12 06:23:54 fedora systemd[1322]: Started pipewire.service - PipeWire Multimedia Service.
apr 12 06:28:48 fedora systemd[1322]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 12 06:28:48 fedora systemd[1322]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot be626c4730724eedad722f071704a526 --
apr 12 22:49:02 fedora systemd[1348]: Started pipewire.service - PipeWire Multimedia Service.
apr 12 22:58:21 fedora systemd[1348]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 12 22:58:21 fedora systemd[1348]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 01266cdcb2d044b2bd4111a1511e0d50 --
apr 13 13:19:26 fedora systemd[1334]: Started pipewire.service - PipeWire Multimedia Service.
apr 13 13:21:14 fedora systemd[1334]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 13 13:21:14 fedora systemd[1334]: Stopped pipewire.service - PipeWire Multimedia Service.
-- Boot 96d59407835649d79580eb8e6e8f002b --
apr 13 13:21:55 fedora systemd[1325]: Started pipewire.service - PipeWire Multimedia Service.
```

**wpctl status**
```bash
PipeWire 'pipewire-0' [1.4.1, user@fedora, cookie:3426947033]
 └─ Clients:
        34. pipewire                            [1.4.1, user@fedora, pid:1578]
        35. cosmic-osd                          [1.4.1, user@fedora, pid:1524]
        41. cosmic-osd                          [1.4.1, user@fedora, pid:1589]
        47. Firefox                             [1.4.1, user@fedora, pid:2988]
        49. WirePlumber                         [1.4.1, user@fedora, pid:7926]
        54. xdg-desktop-portal                  [1.4.1, user@fedora, pid:1767]
        55. MainConn                            [1.4.1, user@fedora, pid:1771]
        56. cosmic-osd                          [1.4.1, user@fedora, pid:1771]
        63. WirePlumber [export]                [1.4.1, user@fedora, pid:7926]
        73. balance                             [1.4.1, user@fedora, pid:1771]
        79. WirePlumber                         [1.4.1, user@fedora, pid:7926]
        99. firefox                             [1.4.1, user@fedora, pid:2988]
       114. Firefox                             [1.4.1, user@fedora, pid:2988]
       117. wpctl                               [1.4.1, user@fedora, pid:8449]

Audio
 ├─ Devices:
 │      76. Built-in Audio                      [alsa]
 │      78. Built-in Audio                      [alsa]
 │
 ├─ Sinks:
 │      57. Built-in Audio Headphones           [vol: 1.00]
 │      58. Raw Speaker Device (do not use)     [vol: 1.00]
 │
 ├─ Sources:
 │      51. Built-in Audio Headset Microphone   [vol: 1.00]
 │
 ├─ Filters:
 │    - filter-chain-7926-19
 │      84. effect_output.j414-convolver                                 [Stream/Output/Audio]
 │  *   86. audio_effect.j414-convolver                                  [Audio/Sink]
 │
 └─ Streams:

Video
 ├─ Devices:
 │      75. FaceTime HD Camera                  [v4l2]
 │
 ├─ Sinks:
 │
 ├─ Sources:
 │  *  112. FaceTime HD Camera (V4L2)
 │
 ├─ Filters:
 │
 └─ Streams:

Settings
 └─ Default Configured Devices:
```

[pw-cli.txt](https://github.com/user-attachments/files/19725421/pw-cli.txt)


Bonus:

1. If I mute volume and I try to raise up it stay mute until I un-mute with the mute key.
2. I have volume up/down keys swapped.

**Comment by chadmed** [comment]
You unhid the wrong node. You need to unhide `AppleJ414HPAI`, not `AppleJ414`. The difference matters.

Also, it's `journalctl --user -u wireplumber`. The extra `--` was a typo sorry

**Comment by chadmed** [comment]
Hmm, your dmesg shows that AOP has been probed, but nothing's happened. What is the output of `arecord -l`?

**Comment by luca-trigili** [comment]
```bash
arecord -i
Warning: Some sources (like microphones) may produce inaudible results
         with 8-bit sampling. Use '-f' argument to increase resolution
         e.g. '-f S16_LE'.
Recording WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
RIFF$WAVEfmt @data^CAborted by signal Interrupt...
```

**Comment by chadmed** [comment]
Can you delete `~/.local/state/wireplumber` and restart wireplumber again using `systemctl restart --user wireplumber`?

Then post the outputs of:
`wpctl status`
`pw-cli i all`
`journalctl --user -u wireplumber`
`jourlanctl --user -u pipewire`
again please? This time in a separate comment.

I'm trying to see if this is something to do with the ALSA UCM files not being parsed correctly

**Comment by luca-trigili** [comment]
**wpctl status**
```bash
PipeWire 'pipewire-0' [1.4.1, user@fedora, cookie:2422715902]
 └─ Clients:
        34. pipewire                            [1.4.1, user@fedora, pid:1585]
        35. cosmic-osd                          [1.4.1, user@fedora, pid:1530]
        40. cosmic-osd                          [1.4.1, user@fedora, pid:1592]
        50. xdg-desktop-portal                  [1.4.1, user@fedora, pid:1776]
        51. MainConn                            [1.4.1, user@fedora, pid:1771]
        52. cosmic-osd                          [1.4.1, user@fedora, pid:1771]
        59. Firefox                             [1.4.1, user@fedora, pid:3000]
        60. WirePlumber                         [1.4.1, user@fedora, pid:36957]
        78. WirePlumber [export]                [1.4.1, user@fedora, pid:36957]
        93. WirePlumber                         [1.4.1, user@fedora, pid:36957]
        95. wpctl                               [1.4.1, user@fedora, pid:37353]
       102. speech-dispatcher-dummy             [1.4.1, user@fedora, pid:3994]
       108. Firefox                             [1.4.1, user@fedora, pid:4287]
       109. Firefox                             [1.4.1, user@fedora, pid:3000]
       119. balance                             [1.4.1, user@fedora, pid:1771]

Audio
 ├─ Devices:
 │      74. Built-in Audio                      [alsa]
 │      76. Built-in Audio                      [alsa]
 │
 ├─ Sinks:
 │      92. Built-in Audio Headphones           [vol: 1.00]
 │
 ├─ Sources:
 │      91. Built-in Audio Headset Microphone   [vol: 1.00]
 │
 ├─ Filters:
 │    - filter-chain-36957-19
 │  *   58. audio_effect.j414-convolver                                  [Audio/Sink]
 │      66. effect_output.j414-convolver                                 [Stream/Output/Audio]
 │
 └─ Streams:
       104. speech-dispatcher-dummy
            106. output_FL       > MacBook Pro J414 Speakers:playback_FL	[init]
            107. output_FR       > MacBook Pro J414 Speakers:playback_FR	[init]

Video
 ├─ Devices:
 │      54. FaceTime HD Camera                  [v4l2]
 │
 ├─ Sinks:
 │
 ├─ Sources:
 │  *   41. FaceTime HD Camera (V4L2)
 │
 ├─ Filters:
 │
 └─ Streams:

Settings
 └─ Default Configured Devices:
```

**pw-cli i all**

[pw-cli.txt](https://github.com/user-attachments/files/19732054/pw-cli.txt)

**journalctl --user -u wireplumber**
```bash
apr 14 10:18:49 fedora wireplumber[1583]: wireplumber: stopped by signal: Terminated
apr 14 10:18:49 fedora systemd[1330]: Stopping wireplumber.service - Multimedia Service Session Manager...
apr 14 10:18:49 fedora wireplumber[1583]: wireplumber: disconnected from pipewire
apr 14 10:18:49 fedora systemd[1330]: Stopped wireplumber.service - Multimedia Service Session Manager.
apr 14 10:18:49 fedora systemd[1330]: wireplumber.service: Consumed 34.476s CPU time, 59.8M memory peak.
apr 14 10:18:49 fedora systemd[1330]: Started wireplumber.service - Multimedia Service Session Manager.
apr 14 10:18:49 fedora wireplumber[36957]: wp-internal-comp-loader: Loading profile 'main'
apr 14 10:18:49 fedora wireplumber[36957]: wplua: [string "state-stream.lua"]:359: attempt to compare number with table
                                           stack traceback:
                                                   [string "state-stream.lua"]:359: in global 'buildDefaultChannelVolumes'
                                                   [string "state-stream.lua"]:65: in function <[string "state-stream.lua"]:45>
apr 14 10:18:49 fedora wireplumber[36957]: [1:06:39.166979664] [36957]  INFO Camera camera_manager.cpp:327 libcamera v0.4.0
apr 14 10:18:50 fedora wireplumber[36957]: m-lua-scripting: <WpSpaPod:0xaaaae5384ea0> Forcing Speaker route props: <WpDevice:0xaaaae520de60>:
                                             Object: size 136, type Spa:Pod:Object:Param:Route (262153), id Spa:Enum:ParamId:Route (13)
                                               Prop: key Spa:Pod:Object:Param:Route:props (10), flags 00000000
                                                 Object: size 64, type Spa:Pod:Object:Param:Props (262146), id Spa:Enum:ParamId:Route (13)
                                                   Prop: key Spa:Pod:Object:Param:Props:channelVolumes (65544), flags 00000000
                                                     Array: child.size 4, child.type Spa:Float
                                                       Float 1.000000
                                                   Prop: key Spa:Pod:Object:Param:Props:mute (65540), flags 00000000
                                                     Bool false
                                               Prop: key Spa:Pod:Object:Param:Route:index (1), flags 00000000
                                                 Int 0
                                               Prop: key Spa:Pod:Object:Param:Route:device (3), flags 00000000
                                                 Int 0
apr 14 10:18:50 fedora wireplumber[36957]: m-lua-scripting: <WpSpaPod:0xaaaae5382450> Forcing Speaker route props: <WpDevice:0xaaaae520de60>:
                                             Object: size 136, type Spa:Pod:Object:Param:Route (262153), id Spa:Enum:ParamId:Route (13)
                                               Prop: key Spa:Pod:Object:Param:Route:props (10), flags 00000000
                                                 Object: size 64, type Spa:Pod:Object:Param:Props (262146), id Spa:Enum:ParamId:Route (13)
                                                   Prop: key Spa:Pod:Object:Param:Props:channelVolumes (65544), flags 00000000
                                                     Array: child.size 4, child.type Spa:Float
                                                       Float 1.000000
                                                   Prop: key Spa:Pod:Object:Param:Props:mute (65540), flags 00000000
                                                     Bool false
                                               Prop: key Spa:Pod:Object:Param:Route:index (1), flags 00000000
                                                 Int 0
                                               Prop: key Spa:Pod:Object:Param:Route:device (3), flags 00000000
                                                 Int 0
apr 14 10:18:50 fedora wireplumber[36957]: m-lua-scripting: <WpSpaPod:0xaaaae508b330> Forcing Speaker route props: <WpDevice:0xaaaae520de60>:
                                             Object: size 136, type Spa:Pod:Object:Param:Route (262153), id Spa:Enum:ParamId:Route (13)
                                               Prop: key Spa:Pod:Object:Param:Route:props (10), flags 00000000
                                                 Object: size 64, type Spa:Pod:Object:Param:Props (262146), id Spa:Enum:ParamId:Route (13)
                                                   Prop: key Spa:Pod:Object:Param:Props:channelVolumes (65544), flags 00000000
                                                     Array: child.size 4, child.type Spa:Float
                                                       Float 1.000000
                                                   Prop: key Spa:Pod:Object:Param:Props:mute (65540), flags 00000000
                                                     Bool false
                                               Prop: key Spa:Pod:Object:Param:Route:index (1), flags 00000000
                                                 Int 0
                                               Prop: key Spa:Pod:Object:Param:Route:device (3), flags 00000000
                                                 Int 0
```

**jourlanctl --user -u pipewire**
```bash
-- Boot 96d59407835649d79580eb8e6e8f002b --
apr 13 13:21:55 fedora systemd[1325]: Started pipewire.service - PipeWire Multimedia Service.
apr 14 01:53:27 fedora systemd[1325]: Stopping pipewire.service - PipeWire Multimedia Service...
apr 14 01:53:27 fedora systemd[1325]: Stopped pipewire.service - PipeWire Multimedia Service.
apr 14 01:53:27 fedora systemd[1325]: pipewire.service: Consumed 9.631s CPU time, 22.6M memory peak, 8.6M memory swap peak.
-- Boot 80a9da773a4b4cd5a8da275199752934 --
apr 14 09:00:37 fedora systemd[1330]: Started pipewire.service - PipeWire Multimedia Service.
```

**Comment by chadmed** [comment]
In `pavucontrol`, what do you see under Recording Devices?

**Comment by luca-trigili** [comment]
![Image](https://github.com/user-attachments/assets/744138bf-8994-4ab3-87c1-061ef1f49f5b)

Only the one in the pic

**Comment by chadmed** [comment]
Could you please post the output of `ls -lah /sys/class/sound/`

**Comment by luca-trigili** [comment]
**ls -lah /sys/class/sound/**
```bash
total 0
drwxr-xr-x  2 root root 0 14 apr 13.33 .
drwxr-xr-x 76 root root 0 14 apr 13.33 ..
lrwxrwxrwx  1 root root 0 14 apr 13.33 card0 -> ../../devices/platform/soc/2a6c00000.aop/snd_soc_apple_aop.2.auto/sound/card0
lrwxrwxrwx  1 root root 0 14 apr 13.33 card1 -> ../../devices/platform/sound/sound/card1
lrwxrwxrwx  1 root root 0 14 apr 13.33 controlC0 -> ../../devices/platform/soc/2a6c00000.aop/snd_soc_apple_aop.2.auto/sound/card0/controlC0
lrwxrwxrwx  1 root root 0 14 apr 13.33 controlC1 -> ../../devices/platform/sound/sound/card1/controlC1
lrwxrwxrwx  1 root root 0 14 apr 13.33 pcmC0D0c -> ../../devices/platform/soc/2a6c00000.aop/snd_soc_apple_aop.2.auto/sound/card0/pcmC0D0c
lrwxrwxrwx  1 root root 0 14 apr 13.33 pcmC1D0c -> ../../devices/platform/sound/sound/card1/pcmC1D0c
lrwxrwxrwx  1 root root 0 14 apr 13.33 pcmC1D0p -> ../../devices/platform/sound/sound/card1/pcmC1D0p
lrwxrwxrwx  1 root root 0 14 apr 13.33 pcmC1D1p -> ../../devices/platform/sound/sound/card1/pcmC1D1p
lrwxrwxrwx  1 root root 0 14 apr 13.33 pcmC1D2c -> ../../devices/platform/sound/sound/card1/pcmC1D2c
lrwxrwxrwx  1 root root 0 14 apr 13.33 seq -> ../../devices/virtual/sound/seq
lrwxrwxrwx  1 root root 0 14 apr 13.33 timer -> ../../devices/virtual/sound/timer
```

**Comment by luca-trigili** [comment]
Just a ping to know if there is something else that I can do to help solving this bug.

**Comment by chadmed** [comment]
The AOP as implemented on M2 Pro/Max SoCs is slightly different and requires some more RE work unfortunately.

**Comment by PaperPrototype** [comment]
Same issue here (I'm on m2 Macbook Pro) the settings app say's there is no microphone

**Comment by luca-trigili** [comment]
Just an innocent ping @chadmed 

P.S. Should I exchange my Mac Pro M2 Pro with a simple Mac M2 NOT pro? Better battery life & mic 🥲

**Comment by chadmed** [comment]
I will be buying a J416 next week to get to the bottom of this

**Comment by kj-1809** [comment]
Same issue here, for the M2 Macbook pro 14 inch (J414)

**Comment by vxsl** [comment]
same issue, j414c

**Comment by luca-trigili** [comment]
@chadmed did you manage to buy/find one of those M2?

If I can help debugging with my machine lemme know.

Thz in advance for your attention

**Comment by prankstr** [comment]
I'm also experiencing this on my 14" 2023 Macbook Pro M2 Max(J414) with both Fedora Asahi Remix 42/43 and Asahi Alarm.

Also happy to provide diagnostics if needed.

**Comment by VorpalQ** [comment]
After this many months of no progress, is this a -wontfix, or what? This is very basic functionality that people need to use daily, you'd think it'd be a bit higher priority.

**Comment by discapes** [comment]
yeah it's like, what am i even paying for?  
oh wait, i'm not...

**Comment by yllwfsh** [comment]
Agree. It's good to remember this project is open source.

Either contribute or be patient and hope that some day this will get fixed.

**Comment by chadmed** [comment]
I am actually looking at this today, however as with other "basic features" that other people think should be our "priority", I am significantly less motivated to work on it when  we receive comments like this. AUD 3000 is nothing for me to sneeze at, and it is hard to justify dropping on a laptop just to look at one feature. Yes, I will get that money back via the OpenCollective, but I still have a $3000 hole in my wallet between now and getting reimbursed for it and that is not a financially comfortable situation. Please just be patient.

**Comment by PaperPrototype** [comment]
Wait its possible to get money back via Open Collective if you are working on an open source project?? :eyes:

**Comment by chadmed** [comment]
OpenCollective is like Patreon for FOSS projects. People [donate to the project via OpenCollective](https://opencollective.com/asahilinux), and we use that to cover our expenses where required.

**Comment by chadmed** [comment]
Fixed with Asahi kernel 6.17.11

**Comment by Phaestion** [comment]
Hi @chadmed quick question, when will the 6.17.11 kernel come out? I see the 6.17.9 kernel is still the latest on the Fedora Gitlab.

**Comment by discapes** [comment]
I'm unfortunately still not seeing the microphone in pavucontrol. I've reinstalled asahi-audio, pipewire and wireplumber, cleared .local/state/wireplumber and restarted. dmesg: http://dpaste.com/8MUSWH44N

**Comment by Phaestion** [comment]
> Hi [@chadmed](https://github.com/chadmed) quick question, when will the 6.17.11 kernel come out? I see the 6.17.9 kernel is still the latest on the Fedora Gitlab.

FYI, the kernel 6.17.12 came out yesterday for me. I tested this on my M2 MacBook Pro and it is working perfectly now. Thanks a lot for your effort @chadmed!

**Comment by chadmed** [comment]
@discapes 

`[    0.659469] apple-dart 2a6808000.iommu: Limiting DMA range to 0x0000010000000000..0x000003ffffffffff`

Did you update m1n1 with the correct Devicetree (run `update-m1n1`) after installing the new kernel? Our sys-kernel/installkernel hook should've done this for you, unless you don't have that installed somehow.

**Comment by luca-trigili** [comment]
Big kudos to @chadmed thank you man.

P.S. In cosmic DE you need to manually select source in setting panel see image below.

<img width="1922" height="1182" alt="Image" src="https://github.com/user-attachments/assets/b03f298a-c490-410e-b618-c2dfa55727f6" />

<img width="1362" height="698" alt="Image" src="https://github.com/user-attachments/assets/a72873ce-6a2f-4568-b3cc-3c7e78dccb14" />

**Comment by discapes** [comment]
Much thanks, that was indeed the issue! I ran `update-m1n1` and it bricked my device, but after fixing that, the microphone works. (m1n1/uboot booted Fedora's EFI instead of Gentoo's, which tried to load a rootfs I had deleted on purpose - fix was to delete Fedora's EFI partition)
